// Code generated by MockGen. DO NOT EDIT.
// Source: generate_service_iface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIGenerateLinkService is a mock of IGenerateLinkService interface.
type MockIGenerateLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockIGenerateLinkServiceMockRecorder
}

// MockIGenerateLinkServiceMockRecorder is the mock recorder for MockIGenerateLinkService.
type MockIGenerateLinkServiceMockRecorder struct {
	mock *MockIGenerateLinkService
}

// NewMockIGenerateLinkService creates a new mock instance.
func NewMockIGenerateLinkService(ctrl *gomock.Controller) *MockIGenerateLinkService {
	mock := &MockIGenerateLinkService{ctrl: ctrl}
	mock.recorder = &MockIGenerateLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGenerateLinkService) EXPECT() *MockIGenerateLinkServiceMockRecorder {
	return m.recorder
}

// GenerateShortLink mocks base method.
func (m *MockIGenerateLinkService) GenerateShortLink() (string, int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateShortLink")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	return ret0, ret1
}

// GenerateShortLink indicates an expected call of GenerateShortLink.
func (mr *MockIGenerateLinkServiceMockRecorder) GenerateShortLink() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateShortLink", reflect.TypeOf((*MockIGenerateLinkService)(nil).GenerateShortLink))
}
